### List all blogs
GET http://localhost:3000/api/blogs

### List just one blog
GET http://localhost:3000/api/blogs/66b3506aed2d3d9e06d2a024/

### Listing a blog doesnt exist
GET http://localhost:3000/api/blogs/66b35eb98029247a82ccaf51

### Creating blog
POST http://localhost:3000/api/blogs
Content-Type: application/json

{
    "title": "test",
    "content": "test"
}

### Creating blog without a paramtter and getting an error
POST http://localhost:3000/api/blogs
Content-Type: application/json

{
    "title": "My second blog"
}

### Update a blog
PATCH http://localhost:3000/api/blogs
Content-Type: application/json

{
    "id": "66b4a74e35ec4675ca82f73c",
    "title": "Yippii",
    "content": "new Content"
}

### delete Blog by Id

DELETE http://localhost:3000/api/blogs/
Content-Type: application/json

{
    "id" : "66b35925a5c8f14230d2124d"
}

### Hmm

GET http://localhost:3000/hmm

### ssr

GET http://localhost:3000/