### List all blogs
GET http://localhost:3000/api/blogs

### List just one blog
GET http://localhost:3000/api/blogs/66b3506aed2d3d9e06d2a024/

### Listing a blog doesnt exist
GET http://localhost:3000/api/blogs/66b35eb98029247a82ccaf51

### Creating blog
POST http://localhost:3000/api/blogs
Content-Type: application/json

{
    "title": "First Blog",
    "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus quae fugit est sint quia cupiditate? Dolor asperiores cum quae, incidunt sunt, dolorum cupiditate alias odio magni quis, accusamus unde consequuntur!asfdasdffasasfdasdf",
    "author": "deneme"
}

### Creating blog without a paramtter and getting an error
POST http://localhost:3000/api/blogs
Content-Type: application/json

{
    "title": "My second blog"
}

### Update a blog
PATCH http://localhost:3000/api/blogs
Content-Type: application/json

{
    "id": "66c7365a744c5419d5c3534a",
    "title": "Yippii",
    "content": "new Content",
    "image": "test",
    "tags" : ["test","naber"]
}

### delete Blog by Id

DELETE http://localhost:3000/api/blogs/
Content-Type: application/json

{
    "id" : "66b34f5f3c9ce529a33ad240"
}

### DELETING ALL BLOGS!!

DELETE  http://localhost:3000/api/blogs/confirm

### Hmm

GET http://localhost:3000/hmm

### ssr

GET http://localhost:3000/